spring.application.name=Shooter

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s
server.port=${SERVER_PORT:8080}
server.name=Shooter Server Main
server.major=0
server.minor=0
server.patch=4

server.forward-headers-strategy=FRAMEWORK

spring.datasource.url=jdbc:postgresql://localhost:5432/shooter
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=OFF

logging.file.name=${LOGS_ROOT:shooter-logs}/shooter.log
logging.logback.rollingpolicy.max-file-size=100MB
logging.logback.rollingpolicy.max-history=0
logging.logback.rollingpolicy.total-size-cap=0

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

unity-server.hook-url=${UNITY_SERVER_HOOK_URL:http://localhost:9090/hooks}
